-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Top 10 Table
create table if not exists public.top10 (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  movie_id int not null,
  title text not null,
  poster_path text,
  backdrop_path text,
  vote_average float,
  release_date text,
  overview text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Watched Table
create table if not exists public.watched (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  movie_id int not null,
  title text not null,
  poster_path text,
  backdrop_path text,
  vote_average float,
  release_date text,
  overview text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table public.top10 enable row level security;
alter table public.watched enable row level security;

-- Top 10 Policies
create policy "Users can view their own top10" on public.top10
  for select using (auth.uid() = user_id);

create policy "Users can insert into their own top10" on public.top10
  for insert with check (auth.uid() = user_id);

create policy "Users can delete from their own top10" on public.top10
  for delete using (auth.uid() = user_id);

-- Watched Policies
create policy "Users can view their own watched" on public.watched
  for select using (auth.uid() = user_id);

create policy "Users can insert into their own watched" on public.watched
  for insert with check (auth.uid() = user_id);

create policy "Users can delete from their own watched" on public.watched
  for delete using (auth.uid() = user_id);
